Added/Update new Enum and View required for Fortify Integration
blackducksoftware/hub-common-response pull request #3
Opened 2017-07-19 16:10 UTC by msenmurugan

Added/Update new Enum and View required for Fortify Integration

2017-07-19 16:20 UTC, jrichardBD commented on src/main/java/com/blackducksoftware/integration/hub/model/view/components/MetaView.java
> +        super();
Please delete the super(); from the constructor

2017-07-19 16:21 UTC, jrichardBD commented on src/main/java/com/blackducksoftware/integration/hub/model/view/components/MetaView.java
> +    public class LinkView extends HubComponent {
Can we move LinkView into its own file?

2017-07-19 16:22 UTC, jamesrichard91 requested changes
Please see my comments in the MetaView class

2017-07-19 17:04 UTC, msenmurugan commented on src/main/java/com/blackducksoftware/integration/hub/model/view/components/MetaView.java
> +        super();
Removed Super() from the constructor

2017-07-19 17:05 UTC, msenmurugan commented on src/main/java/com/blackducksoftware/integration/hub/model/view/components/MetaView.java
> +    public class LinkView extends HubComponent {
Created a new LinkView under Components

2017-07-19 17:07 UTC, jamesrichard91 approved these changes
Looks good to me

2017-07-19 17:28 UTC, psantos1113 approved these changes

2017-07-19 19:02 UTC, psantos1113 requested changes
Don't use get methods use public fields. Missed that earlier.  ekerwin found it so until that is address I can't approve this.

2017-07-19 19:31 UTC, ekerwin commented
Please take a look at the PR for this branch, I think it addresses the final stuff for these changes.

2017-07-21 17:07 UTC, ekerwin approved these changes

2017-07-21 17:42 UTC, stevebillings commented on src/main/java/com/blackducksoftware/integration/hub/model/view/VulnerabilityWithRemediationView.java
> +    public String cweId;
What is cwe? should that maybe be cve?

2017-07-21 17:44 UTC, msenmurugan commented on src/main/java/com/blackducksoftware/integration/hub/model/view/VulnerabilityWithRemediationView.java
> +    public String cweId;
CWE - Common Weakness Enumeration (trademark of MITRE Corporation). BlackDuck is adding those ids in all vulnerabilities

2017-07-21 18:04 UTC, stevebillings commented
Looks good!

2017-07-21 18:05 UTC, stevebillings approved these changes

2017-07-21 20:16 UTC, psantos1113 approved these changes
Looks good

2017-07-21 20:16 UTC, merged